config/routes.rb
Rails.application.routes.draw do
  root to: "admin/admin#index"
  devise_for :users
  
  namespace :admin do
    root to: "admin#index"
    get "/" => "admin#index", as: :index
    get "dashboard" => "admin#dashboard", as: :dashboard
  	namespace :directories do
  	  resources :departments
  	  resources :inventories
      resources :users
      post "departments/get_table"
      post "inventories/get_table"
      post "users/get_table"
  	end
    namespace :it_department do
      resources :works
      post "works/get_works/" => "works#get_works", response_to: :json
      post "works/get_inventory_movings/" => "works#get_inventory_movings", response_to: :json
      post "works/get_projector_jobs/" => "works#get_projector_jobs", response_to: :json
      post "works/create_comment" => "works#create_comment", response_to: :json
      get "works/get_select_data/:select_element" => "works#get_select_data"
    end
  end
  get "admin/admin/import"
end

app/controllers/admin/it_department/works_controller.rb
class Admin::ItDepartment::WorksController < ApplicationController
  layout false
  before_action :set_work, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource class: "ItDepartmentWork"

  def index
  end

  def show
  end

  def get_works
    #Загрузка доступных записей
    @works = ItDepartmentWork.joins(:user, :department).accessible_by(current_ability).where("inventory_move = 0 OR inventory_move = 2").where(projector_job: false).all
    #Удалить стобец "Действия"
    params["columns"].delete("10")
    #Фильтрация по всем столбцам
    params["columns"].each_with_index{|c, i| @works = @works.where("#{c[1]["data"]} LIKE ?", "%#{c[1]["search"]["value"]}%")}
    #Фильтрация по полю "Поиск"
    #@works = @works.where("it_department_works.created_at LIKE ? OR work_description LIKE ? OR users.name LIKE ? OR work_type LIKE ? OR orgtechnik LIKE ? OR departments.name LIKE ? OR client_name LIKE ? OR client_telephone LIKE ? OR end_date LIKE ? or status LIKE ?", "%#{params["search"]["value"]}%", "%#{params["search"]["value"]}%", "%#{params["search"]["value"]}%", "%#{params["search"]["value"]}%", "%#{params["search"]["value"]}%", "%#{params["search"]["value"]}%", "%#{params["search"]["value"]}%", "%#{params["search"]["value"]}%", "%#{params["search"]["value"]}%", "%#{params["search"]["value"]}%")
    #Сортировка по столбцу
    params["columns"]["0"]["data"] = "created_at"
    @filtered_works = @works.count
    @works = @works.offset(params[:start]).limit(params[:length]).order(params["columns"][params["order"]["0"]["column"]]["data"] => params["order"]["0"]["dir"].to_sym)

    #Выборка максимума записей без фильтров
    @total_works = ItDepartmentWork.joins(:user, :department).accessible_by(current_ability).where("inventory_move = 0 OR inventory_move = 2").where(projector_job: false).count
  end

  def get_inventory_movings
    #Загрузка доступных записей
    @works = ItDepartmentWork.joins(:user, :department).accessible_by(current_ability).where("inventory_move = 1 OR inventory_move = 2").all
    #Удалить стобец "Действия"
    params["columns"].delete("12")
    #Фильтрация по всем столбцам
    params["columns"].each_with_index{|c, i| @works = @works.where("#{c[1]["data"]} LIKE ?", "%#{c[1]["search"]["value"]}%")}
    #Фильтрация по полю "Поиск"
    #@works = @works.where("it_department_works.created_at LIKE ? OR work_description LIKE ? OR users.name LIKE ? OR work_type LIKE ? OR orgtechnik LIKE ? OR departments.name LIKE ? OR client_name LIKE ? OR client_telephone LIKE ? OR end_date LIKE ? or status LIKE ?", "%#{params["search"]["value"]}%", "%#{params["search"]["value"]}%", "%#{params["search"]["value"]}%", "%#{params["search"]["value"]}%", "%#{params["search"]["value"]}%", "%#{params["search"]["value"]}%", "%#{params["search"]["value"]}%", "%#{params["search"]["value"]}%", "%#{params["search"]["value"]}%", "%#{params["search"]["value"]}%")
    #Сортировка по столбцу
    params["columns"]["0"]["data"] = "created_at"
    @works = @works.offset(params[:start]).limit(params[:length]).order(params["columns"][params["order"]["0"]["column"]]["data"] => params["order"]["0"]["dir"].to_sym)
    #Выборка максимума записей без фильтров
    @total_works = ItDepartmentWork.joins(:user, :department).accessible_by(current_ability).where("inventory_move = 1 OR inventory_move = 2").count
  end

  def get_projector_jobs
    #Загрузка доступных записей
    @works = ItDepartmentWork.joins(:user, :department, :projector).accessible_by(current_ability).where(projector_job: true).all
    #Удалить стобец "Действия"
    params["columns"].delete("9")
    #Фильтрация по всем столбцам
    params["columns"].each_with_index{|c, i| @works = @works.where("#{c[1]["data"]} LIKE ?", "%#{c[1]["search"]["value"]}%")}
    #Фильтрация по полю "Поиск"
    #@works = @works.where("it_department_works.created_at LIKE ? OR work_description LIKE ? OR users.name LIKE ? OR work_type LIKE ? OR orgtechnik LIKE ? OR departments.name LIKE ? OR client_name LIKE ? OR client_telephone LIKE ? OR end_date LIKE ? or status LIKE ?", "%#{params["search"]["value"]}%", "%#{params["search"]["value"]}%", "%#{params["search"]["value"]}%", "%#{params["search"]["value"]}%", "%#{params["search"]["value"]}%", "%#{params["search"]["value"]}%", "%#{params["search"]["value"]}%", "%#{params["search"]["value"]}%", "%#{params["search"]["value"]}%", "%#{params["search"]["value"]}%")
    #Сортировка по столбцу
    params["columns"]["0"]["data"] = "created_at"
    @works = @works.offset(params[:start]).limit(params[:length]).order(params["columns"][params["order"]["0"]["column"]]["data"] => params["order"]["0"]["dir"].to_sym)
    #Выборка максимума записей без фильтров
    @total_works = ItDepartmentWork.joins(:user, :department, :projector).accessible_by(current_ability).where(projector_job: true).count
  end

  def create_comment
    @work = ItDepartmentWork.find(params[:work_id])
    @comment = ItDepartmentWorkComment.create(it_department_work_id: @work.id, comment: params[:comment])
    respond_to do |format|
      if @comment.save
        format.js { render js: "window.location.reload()", notice: "Комментарий добавлен"}
      else
        format.js { render js: "alert('Не удалось добавить комментарий')" }
      end
    end
  end

  def new
    @work = ItDepartmentWork.new
  end

  def create
    @work = ItDepartmentWork.new(work_params)
    @work.user_id ||= current_user.id
    respond_to do |format|
      if @work.save
        format.js { render js: "window.location = '/admin#/admin/it_department/works'", notice: "Работа добавлена"}
      else
        format.js { render "failed", alert: "Не удалось создать запись" }
      end
    end
  end

  def edit
  end

  def update
    @work.user_id ||= current_user.id
    respond_to do |format|
      if @work.update(work_params)
        format.js { render js: "window.location = '/admin#/admin/it_department/works'", notice: "Работа обновлена"}
      else
        format.js { render "failed", alert: "Не удалось создать запись" }
      end
    end
  end

  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to "/admin#/admin/it_department/works", notice: 'Запись удалена' }
    end
  end

  def get_select_data
    case params[:select_element]
    when "projector"
      results = Projector.where("name LIKE ? OR location LIKE ?", "%#{params[:q]}%", "%#{params[:q]}%").limit(25).select(:id).select("CONCAT(name, ' - ', location) as text")
    when "inventory"
      results = Inventory.where("name LIKE ? OR number LIKE ? or client_name LIKE ? or place LIKE ?", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%").limit(25).select(:id).select("CONCAT(IFNULL(number, ''), ' - ', IFNULL(name, ''), ', ', IFNULL(place, ''), ', ', IFNULL(client_name, '')) as text")
    when "user"
      results = User.where("name LIKE ?", "%#{params[:q]}%").limit(25).select(:id).select("name as text")
    when "department"
      results = Department.where("name LIKE ?", "%#{params[:q]}%").limit(25).select(:id).select("name as text")
    end
    render json: {more: false, results: results} 
  end

  private

  def set_work
    @work = ItDepartmentWork.find(params[:id])
  end

  def work_params
    params.require(:it_department_work).permit(:work_type, :user_id, :work_description, :orgtechnik, :inventory_move, :end_date, :department_id, :client_name, :client_telephone, :status, :inventory, :other_inventory, :from_department_id, :detailed_from_client_place, :inventory_move_from_client_name, :inventory_move_from_client_telephone, :detailed_client_place, :inventory_move_type, :projector_job, :inventory_move_destination_department_id, :inventory_move_destination_client_place, :inventory_move_destination_client_name, :inventory_move_destination_client_telephone, :projector_id, :projector_work_type, :projector_lamp_run_time, :projector_filter_run_time, :projector_filter_clean, :projector_lamp_replace, :projector_runtime_check, :projector_other, :projector_other_description, :orgtechnik_inventory, :orgtechnik_toner_replace, :orgtechnik_print_replace, :orgtechnik_other, :orgtechnik_other_description)
  end
end

app/helpers/admin/it_department/works_helper.rb
module Admin::ItDepartment::WorksHelper
end

app/views/admin/it_department/works/edit.html.haml
= alerts_and_notices
%section#widget-grid
  .row
    %article.col-xs-12.col-sm-12.col-md-12.col-lg-12
      #wid-id-0.jarviswidget.jarviswidget-color-darken{:"data-widget-colorbutton" => "false", :"data-widget-editbutton" => "false", :"data-widget-sortable" => "false", :"data-widget-togglebutton" => "false", :"data-widget-deletebutton" => "false", :"data-widget-fullscreenbutton" => "false"}
        %header
          %h2
            %strong Редактирование записи
        %div
          .widget-body
            = render 'form'
            = link_to 'Назад', "/admin#/admin/it_department/works"
:coffeescript
  $ ->
    pageSetUp()

app/views/admin/it_department/works/failed.js.erb
$('#content').html('<%=j render 'form' %>')

app/views/admin/it_department/works/new.html.haml
= alerts_and_notices
%section#widget-grid
  .row
    %article.col-xs-12.col-sm-12.col-md-12.col-lg-12
      #wid-id-0.jarviswidget.jarviswidget-color-darken{:"data-widget-colorbutton" => "false", :"data-widget-editbutton" => "false", :"data-widget-sortable" => "false", :"data-widget-togglebutton" => "false", :"data-widget-deletebutton" => "false", :"data-widget-fullscreenbutton" => "false"}
        %header
          %h2
            %strong Новая запись
        %div
          .widget-body
            = render 'form'
            = link_to 'Назад', "/admin#/admin/it_department/works"
:coffeescript
  $ ->
    pageSetUp()

app/views/admin/it_department/works/show.html.haml
= alerts_and_notices
%section#widget-grid
  .row
    %article.col-xs-12.col-sm-12.col-md-12.col-lg-12
      #wid-id-1.jarviswidget.jarviswidget-color-darken{:"data-widget-colorbutton" => "false", :"data-widget-editbutton" => "false", :"data-widget-sortable" => "false", :"data-widget-togglebutton" => "false", :"data-widget-deletebutton" => "false", :"data-widget-fullscreenbutton" => "false"}
        %header
          %h2
            %strong Просмотр работы
        %div
          .widget-body
            %table.table.table-bordered.table-striped.table-hover
              - if @work.projector_job?
                %tr
                  %td.col-md-2 Работа связана с проекторами
                  %td.col-md-10
                    %i.fa.fa-check-square-o
                %tr
                  %td.col-md-2 Проектор
                  %td.col-md-10= @work.projector.name
                %tr
                  %td.col-md-2 Чистка фильтра
                  %td.col-md-10= @work.projector_filter_clean? ? "<i class='fa fa-check-square-o'></i>".html_safe : "<i class='fa fa-square-o'></i>".html_safe
                %tr
                  %td.col-md-2 Замена лампы
                  %td.col-md-10= @work.projector_lamp_replace? ? "<i class='fa fa-check-square-o'></i>".html_safe : "<i class='fa fa-square-o'></i>".html_safe
                %tr
                  %td.col-md-2 Проверка наработки
                  %td.col-md-10= @work.projector_runtime_check? ? "<i class='fa fa-check-square-o'></i>".html_safe : "<i class='fa fa-square-o'></i>".html_safe
                %tr
                  %td.col-md-2 Другое
                  %td.col-md-10= @work.projector_other? ? @work.projector_other_description : "<i class='fa fa-square-o'></i>".html_safe
                %tr
                  %td.col-md-2 Наработка фильтра
                  %td.col-md-10= @work.projector_filter_run_time
                %tr
                  %td.col-md-2 Наработка лампы
                  %td.col-md-10= @work.projector_lamp_run_time
              - if @work.orgtechnik?
                %tr
                  %td.col-md-2 Работа связана с оргтехникой
                  %td.col-md-10
                    %i.fa.fa-check-square-o
                %tr
                  %td.col-md-2 Оргтехника
                  %td.col-md-10= @work.orgtechnik_inventory.try(:name)
                %tr
                  %td.col-md-2 Замена тонер-картриджа
                  %td.col-md-10= @work.orgtechnik_toner_replace? ? "<i class='fa fa-check-square-o'></i>".html_safe : "<i class='fa fa-square-o'></i>".html_safe
                %tr
                  %td.col-md-2 Замена принт-картриджа
                  %td.col-md-10= @work.orgtechnik_print_replace? ? "<i class='fa fa-check-square-o'></i>".html_safe : "<i class='fa fa-square-o'></i>".html_safe
                %tr
                  %td.col-md-2 Другое
                  %td.col-md-10= @work.orgtechnik_other? ? @work.orgtechnik_other_description : "<i class='fa fa-square-o'></i>".html_safe
              - if @work.inventory_move == 0 or @work.inventory_move == 2
                
              
                %tr
                  %td.col-md-2 Срочность
                  %td.col-md-10= ItDepartmentWork::WORK_TYPE[@work.work_type]
                %tr
                  %td.col-md-2 Исполнитель
                  %td.col-md-10= @work.user.name
                %tr
                  %td.col-md-2 Описание работы
                  %td.col-md-10= @work.work_description
                %tr
                  %td.col-md-2 Планируемое завершение
                  %td.col-md-10= @work.end_date.strftime("%d.%m.%Y")
                %tr
                  %td.col-md-2 Подразделение
                  %td.col-md-10= @work.department.name
                %tr
                  %td.col-md-2 Корпус, этаж, кабинет
                  %td.col-md-10= @work.detailed_client_place
                %tr
                  %td.col-md-2 Ф.И.О. заказавшего работу
                  %td.col-md-10= @work.client_name
                %tr
                  %td.col-md-2 Телефон заказавшего работу
                  %td.col-md-10= @work.client_telephone
              - if @work.inventory_move == 1 or @work.inventory_move == 2
                %tr
                  %td.col-md-2 Тип перемещения
                  %td.col-md-10= ItDepartmentWork::INV_MOVE_TYPE[@work.inventory_move_type.to_i]
                %tr
                  %td.col-md-2 МТЦ
                  %td.col-md-10= Inventory.find_by(id: @work.inventory.to_i).nil? ? @work.other_inventory : Inventory.find_by(id: @work.inventory.to_i).try(:name)
                %tr
                  %td.col-md-2 Исходное подразделение
                  %td.col-md-10= Department.find_by(id: @work.from_department_id).try(:name)
                %tr
                  %td.col-md-2 Корпус, этаж, кабинет
                  %td.col-md-10= @work.detailed_from_client_place
                %tr
                  %td.col-md-2 Ф.И.О. предыдущего мат. ответственного
                  %td.col-md-10= @work.inventory_move_from_client_name
                %tr
                  %td.col-md-2 Телефон предыдущего мат. ответственного
                  %td.col-md-10= @work.inventory_move_from_client_telephone
                %tr
                  %td.col-md-2 Конечное подразделение
                  %td.col-md-10= Department.find_by(id: @work.inventory_move_destination_department_id).try(:name)
                %tr
                  %td.col-md-2 Корпус, этаж, кабинет (конечное назначение)
                  %td.col-md-10= @work.inventory_move_destination_client_place
                %tr
                  %td.col-md-2 Ф.И.О. назначенного мат. ответственного
                  %td.col-md-10= @work.inventory_move_destination_client_name
                %tr
                  %td.col-md-2 Телефон назначенного мат. ответственного
                  %td.col-md-10= @work.inventory_move_destination_client_telephone

  .row
    %article.col-xs-12.col-sm-12.col-md-12.col-lg-12
      #wid-id-0.jarviswidget.jarviswidget-color-red{:"data-widget-colorbutton" => "false", :"data-widget-editbutton" => "false", :"data-widget-sortable" => "false", :"data-widget-togglebutton" => "false", :"data-widget-deletebutton" => "false", :"data-widget-fullscreenbutton" => "false"}
        %header
          %h2
            %strong Изменение статуса
        %div
          .widget-body
            = form_for [:admin, @work], html: {class: "form-horizontal", novalidate: true}, remote: true do |f|
              .form-group
                %label.col-md-2.contol-label= f.label :status
                .col-md-10.smart-form
                  = label_tag :nil, class: "select #{"state-error" if !@work.errors[:status].empty? }" do
                    = f.select :status, options_for_select(ItDepartmentWork::STATUS.collect{|v,i| [v, ItDepartmentWork::STATUS.index(v)]}, selected: @work.status)
                    %i
              .form-actions
                = f.submit "Изменить", class: "btn btn-primary", id: "hide_this_btn"
  .row
    %article.col-xs-12.col-sm-12.col-md-12.col-lg-12
      #wid-id-2.jarviswidget.jarviswidget-color-green{:"data-widget-colorbutton" => "false", :"data-widget-editbutton" => "false", :"data-widget-sortable" => "false", :"data-widget-togglebutton" => "false", :"data-widget-deletebutton" => "false", :"data-widget-fullscreenbutton" => "false"}
        %header
          %h2
            %strong Комментарии
        %div
          .widget-body
            = form_tag admin_it_department_works_create_comment_path, class: "form-horizontal", novalidate: true, remote: true do
              %fieldset
                = hidden_field_tag :work_id, @work.id
                .form-group
                  %label.col-md-2.contol-label Добавить комментарий
                  .col-md-10.smart-form
                    = label_tag :nil, class: "textarea" do
                      %i.icon-prepend.fa.fa-comment

                      = text_area_tag :comment, nil, placeholder: "Комментарий"
                .form-actions
                  = submit_tag "Отправить", class: "btn btn-lg btn-primary"
            - @work.it_department_work_comments.each do |comment|
              %blockquote
                %p= comment.comment
                %small= comment.created_at.strftime("%d.%m.%Y")
              

  = link_to 'Назад', "/admin#/admin/it_department/works"
:coffeescript
  $ ->
    pageSetUp()