config/routes.rb
Rails.application.routes.draw do
  root to: "admin/admin#index"
  devise_for :users
  
  namespace :admin do
    root to: "admin#index"
    get "/" => "admin#index", as: :index
    get "dashboard" => "admin#dashboard", as: :dashboard
  	namespace :directories do
  	  resources :departments
  	  resources :inventories
      resources :users
      post "departments/get_table"
      post "inventories/get_table"
      post "users/get_table"
  	end
    namespace :it_department do
      resources :works
      post "works/get_works/" => "works#get_works", response_to: :json
      post "works/get_inventory_movings/" => "works#get_inventory_movings", response_to: :json
      post "works/get_projector_jobs/" => "works#get_projector_jobs", response_to: :json
      post "works/create_comment" => "works#create_comment", response_to: :json
      get "works/get_select_data/:select_element" => "works#get_select_data"
    end
  end
  get "admin/admin/import"
end

app/views/layouts/admin.html.haml
- require 'digest/md5'
- email_address = current_user.email.downcase
- avatar_hash = Digest::MD5.hexdigest(email_address)
!!!
%html{lang: "ru-RU"}
  %head
    %meta{charset: "utf-8"}/
    %title= @title ? "#{@title} - ТГМУ" : "ТГМУ"
    %meta{content: "Панель управления сайтом", name: "description"}/
    %meta{content: "Тихоокеанский государственный медицинский университет", name: "author"}/
    %meta{content: "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no", name: "viewport"}/

    %link{href: "http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,300,700&subset=latin,cyrillic", rel: "stylesheet"}/
    = stylesheet_link_tag 'admin', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags

    %link{rel: "shortcut icon", href: "/favicon.ico", type: "image/x-icon"}
    %link{rel: "icon", href: "/favicon.ico", type: "image/x-icon"}


  %body.fixed-header.fixed-navigation.fixed-ribbon.fixed-footer
    %header#header
      #logo-group
        %span#logo
          %img{alt: "ТГМУ", src: asset_path("logo.png")}/

      .pull-right
        #hide-menu.btn-header.pull-right
          %span
            %a{"data-action" => "toggleMenu", href: "javascript:void(0);", title: "Свернуть меню"}
              %i.fa.fa-reorder

        #logout.btn-header.transparent.pull-right
          %span
            = link_to destroy_user_session_path, "data-action" => "userLogout", "data-logout-msg" => "До свидания!", title: "Выход" do
              %i.fa.fa-sign-out
        #fullscreen.btn-header.transparent.pull-right
          %span
            %a{"data-action" => "launchFullscreen", href: "javascript:void(0);", title: "Full Screen"}
              %i.fa.fa-arrows-alt

    %aside#left-panel
      .login-info
        %span
          = link_to "#" do
            = image_tag "http://www.gravatar.com/avatar/#{avatar_hash}"
            %span
              = current_user.name
      %nav
        %ul
          %li
            = link_to admin_dashboard_path do
              %i.fa.fa-lg.fa-fw.fa-bar-chart-o
              %span.menu-item-parent Панель управления
          %li
            %a{href: "#"}
              %i.fa.fa-lg.fa-fw.fa-desktop
              %span.menu-item-parent IT Отдел
            %ul
              %li
                = link_to "Работы", admin_it_department_works_path
          - if can? :manage, Department or 
          - can? :manage, Inventory or
          - can? :manage, User
            %li
              %a{href: "#"}
                %i.fa.fa-lg.fa-fw.fa-book
                %span.menu-item-parent Справочники
              %ul
                - if can? :manage, Department
                  %li= link_to "Подразделения ТГМУ", admin_directories_departments_path
                - if can? :manage, Inventory
                  %li= link_to "МТЦ", admin_directories_inventories_path
                - if can? :manage, User
                  %li= link_to "Пользователи", admin_directories_users_path

    #main{role: "main"}
      #ribbon
        %ol.breadcrumb
      #content

    .page-footer
      .row
        .col-xs-12.col-sm-8
          %span.txt-color-white.hidden-xs Тихоокеанский государственный медицинский университет.
          %span.txt-color-white.hidden-md.hidden-lg ТГМУ
          %span.text-muted.hidden-xs По техническим вопросам обращайтесь по тел. 242-96-32
        .col-xs-6.col-sm-4.text-right.hidden-xs
          

    = javascript_include_tag 'admin'

    :javascript
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-54326713-1']);
      _gaq.push(['_trackPageview']);
        
      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

app/views/layouts/application.html.haml
= yield